# See http://travis-ci.org/encukou/pytmxlib

language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
install:
  - python setup.py develop
  - sudo apt-get install python-lxml
  - pip install pytest-cov
script: py.test
